name: 00-workflow-hello # (optional) workflow name (appearing in Actions tab)
on: [push]
jobs:
  hello-job: # job name
    runs-on: ubuntu-latest # run on Ubuntu on a fresh VM hosted by GH
    steps:
      - uses: actions/checkout@v2   # to checkout the repo to runner
      - run: cat README.md
